# Eureka服务器实例1配置
server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles: peer1

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
    # 添加重试机制
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
    response-cache-update-interval-ms: 2000
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 2000
    # 等待启动
    wait-time-in-ms-when-sync-empty: 5

# 日志配置，方便调试
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO 